### ISSUE TITLE
Allow to map code sources to doc sources

### ISSUE THREAD

**Issue by olena-zmiiova** [SpineEventEngine/embed-code#61]
Currently, `embed-code` can be configured with only one `code-path` and `doc-path`. When mapping another code source for one of the subfolders, or we have a few code/doc paths, we need to define separate config files and rerun them. To make the tool easier to configure, there might be a special field with the list of such mappings:

```
code-path: "test/resources/code/java"
docs-path: "test/resources/docs"
embed-mappings:
  - code-path: "test/resources/code/kotlin"
    docs-path: "test/resources/docs/kotlin"
```
